---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ContainerImageUri:
    Type: String
    Description: 'uri of the container image'
  EcsClusterName:
    Type: String
    Description: 'name of the ecs cluster'
  NetworkSubnet:
    Type: String
    Description: 'network subnet in vpc'
  NetworkSecurityGroup:
    Type: String
    Description: 'network security group in vpc'
Resources:
  MyTaskExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'ecs-tasks.amazonaws.com'
            Action: 'sts:AssumeRole'
      Path: '/'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'

  MyTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      ExecutionRoleArn: !Ref MyTaskExecutionRole
      Cpu: '512'
      Memory: '1024'
      RequiresCompatibilities:
        - 'FARGATE'
      NetworkMode: 'awsvpc'
      ContainerDefinitions:
        - Name: 'golang-hello'
          Image: !Ref ContainerImageUri
          Memory: '512'
  MyService:
    Type: 'AWS::ECS::Service'
    Properties:
      TaskDefinition: !Ref MyTaskDefinition
      Cluster: !Ref EcsClusterName
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !Ref NetworkSecurityGroup
          Subnets:
            - !Ref NetworkSubnet
            
