---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyTaskExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'MyTaskExecutionRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'ecs-tasks.amazonaws.com'
            Action: 'sts:AssumeRole'
      Path: '/'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'

  MyTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      ExecutionRoleArn: !Ref MyTaskExecutionRole
      Cpu: '512'
      Memory: '1024'
      ContainerDefinitions:
        - Name: 'golang-hello'
          Image: '[AWS_ACCOUNT_ID].dkr.ecr.us-east-1.amazonaws.com/[IMAGE:TAG]'
          Memory: '512'
