apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-hello
spec:
  replicas: 1
    spec:
      containers:
      - image: [AWS_ACCOUNT_ID].dkr.ecr.us-east-1.amazonaws.com/[IMAGE:TAG]
      imagePullSecrets:
      - name: ecr-pull-secret
